name: Secret Scanning

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  secret-scanning-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
          ref: main

      - name: Run secret scanning
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: '.gitleaks.toml'

  secret-scanning-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0
          ref: dev

      - name: Run secret scanning
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_CONFIG: '.gitleaks.toml'

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [secret-scanning-main, secret-scanning-dev]
    if: always()
    steps:
      - name: Send Discord Notification
        uses: sarisia/actions-status-discord@v1.16.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ needs.secret-scanning-main.result != 'failure' && needs.secret-scanning-dev.result != 'failure' && 'success' || 'failure' }}
          title: 'Secret Scanning'
          description: |
            **Triggered by:** ${{ github.actor }}
            **Branch:** ${{ github.ref_name }}
            **Repository:** ${{ github.repository }}
          url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          username: GitHub Actions
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
